# Generated by Django 2.2.5 on 2019-11-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phoneno',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
