# Generated by Django 2.2.5 on 2019-11-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cart_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
