# Generated by Django 2.2.5 on 2019-11-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191103_1447'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='home_product',
        ),
    ]
